namespace MeshcomWebDesk.Models;

/// <summary>
/// Statische Liste aller bekannten MeshCom-Konsolenbefehle (aus --help + --info).
///
/// OptimisticUpdate = true  → Firmware gibt keinen Statuswert zurück.
///                            Nach Timeout (kein Fehler) wird der gesendete Wert übernommen.
/// ParsePattern             → Regex zum Extrahieren des Werts aus der Console-Ausgabe.
/// </summary>
public static class ConsoleCommandDefinitions
{
    public static readonly IReadOnlyList<ConsoleCommandDef> All =
    [
        // ── LoRa ─────────────────────────────────────────────────────────
        new() { Name = "txfreq",        Group = ConsoleCommandGroup.LoRa, Type = ConsoleCommandType.Value,
                Description = "TX Frequenz",      Unit = "MHz", Min = 400, Max = 520, Step = 0.001,
                ParsePattern = @"FREQ\s+([\d.]+)\s+MHz" },
        new() { Name = "txpower",       Group = ConsoleCommandGroup.LoRa, Type = ConsoleCommandType.Value,
                Description = "TX Sendeleistung", Unit = "dBm", Min = 2, Max = 22, Step = 1,
                ParsePattern = @"TXPWR\s+(\d+)\s+dBm" },
        new() { Name = "txbw",          Group = ConsoleCommandGroup.LoRa, Type = ConsoleCommandType.Value,
                Description = "Bandbreite",       Unit = "kHz",
                Options = ["125", "250", "500"], OptimisticUpdate = true },
        new() { Name = "setboostedgain",Group = ConsoleCommandGroup.LoRa, Type = ConsoleCommandType.Toggle,
                Description = "Boosted RX Gain (RXBOOST)",
                ParsePattern = @"RXBOOST\s+(on|off)" },
        new() { Name = "setctry",       Group = ConsoleCommandGroup.LoRa, Type = ConsoleCommandType.Value,
                Description = "RX/TX-LoRa-Parameter (Land)", Min = 0, Max = 99, Step = 1,
                OptimisticUpdate = true },

        // ── System ───────────────────────────────────────────────────────
        new() { Name = "info",      Group = ConsoleCommandGroup.System, Type = ConsoleCommandType.Action,
                Description = "Node-Info anzeigen" },
        new() { Name = "mheard",    Group = ConsoleCommandGroup.System, Type = ConsoleCommandType.Action,
                Description = "MHeard Liste anzeigen" },
        new() { Name = "setcall",   Group = ConsoleCommandGroup.System, Type = ConsoleCommandType.Text,
                Description = "Rufzeichen (Callsign)",
                ParsePattern = @"Call:\s*<([^>]+)>", OptimisticUpdate = true },
        new() { Name = "setname",   Group = ConsoleCommandGroup.System, Type = ConsoleCommandType.Text,
                Description = "Node-Name",
                ParsePattern = @"NAME:\s*(.+)", OptimisticUpdate = true },
        new() { Name = "utcoff",    Group = ConsoleCommandGroup.System, Type = ConsoleCommandType.Value,
                Description = "UTC-Offset", Unit = "h", Min = -12, Max = 14, Step = 0.5,
                ParsePattern = @"UTC-OFF\s+([-\d.]+)" },
        new() { Name = "maxv",      Group = ConsoleCommandGroup.System, Type = ConsoleCommandType.Value,
                Description = "Max. Batteriespannung (= 100%)", Unit = "V", Min = 3.0, Max = 4.5, Step = 0.01,
                ParsePattern = @"MAXV\s+([\d.]+)\s+V" },
        new() { Name = "contrast",  Group = ConsoleCommandGroup.System, Type = ConsoleCommandType.Value,
                Description = "Display Kontrast", Min = 0, Max = 255, Step = 1,
                ParsePattern = @"contrast\s+(\d+)" },
        new() { Name = "atxt",      Group = ConsoleCommandGroup.System, Type = ConsoleCommandType.Text,
                Description = "APRS Text / Kommentar",
                ParsePattern = @"ATXT:\s*(.+)", OptimisticUpdate = true },
        new() { Name = "settime",   Group = ConsoleCommandGroup.System, Type = ConsoleCommandType.Text,
                Description = "Zeit setzen (yyyy.mm.dd hh:mm:ss)", OptimisticUpdate = false },
        new() { Name = "reboot",    Group = ConsoleCommandGroup.System, Type = ConsoleCommandType.Action,
                Description = "Node Neustart", NeedsConfirm = true },
        new() { Name = "ota-update",Group = ConsoleCommandGroup.System, Type = ConsoleCommandType.Action,
                Description = "OTA-Update starten", NeedsConfirm = true },
        new() { Name = "volt",      Group = ConsoleCommandGroup.System, Type = ConsoleCommandType.Action,
                Description = "Batteriespannung anzeigen" },
        new() { Name = "proz",      Group = ConsoleCommandGroup.System, Type = ConsoleCommandType.Action,
                Description = "Batterie % anzeigen" },
        new() { Name = "pos",       Group = ConsoleCommandGroup.System, Type = ConsoleCommandType.Action,
                Description = "Position anzeigen (lat/lon/alt)" },
        new() { Name = "weather",   Group = ConsoleCommandGroup.System, Type = ConsoleCommandType.Action,
                Description = "Wetter anzeigen (temp/hum/press)" },
        new() { Name = "showI2C",   Group = ConsoleCommandGroup.System, Type = ConsoleCommandType.Action,
                Description = "I²C-Geräte anzeigen" },
        new() { Name = "setinfo",   Group = ConsoleCommandGroup.System, Type = ConsoleCommandType.Toggle,
                Description = "Node-Info senden (on/off)", OptimisticUpdate = true },

        // ── Position ─────────────────────────────────────────────────────
        new() { Name = "sendpos",   Group = ConsoleCommandGroup.GPS, Type = ConsoleCommandType.Action,
                Description = "Position jetzt senden" },
        new() { Name = "setlat",    Group = ConsoleCommandGroup.GPS, Type = ConsoleCommandType.Text,
                Description = "Breitengrad setzen (z.B. 48.12345)", OptimisticUpdate = true },
        new() { Name = "setlon",    Group = ConsoleCommandGroup.GPS, Type = ConsoleCommandType.Text,
                Description = "Längengrad setzen (z.B. 016.12345)", OptimisticUpdate = true },
        new() { Name = "setalt",    Group = ConsoleCommandGroup.GPS, Type = ConsoleCommandType.Text,
                Description = "Höhe setzen (m)", OptimisticUpdate = true },
        new() { Name = "symid",     Group = ConsoleCommandGroup.GPS, Type = ConsoleCommandType.Text,
                Description = "APRS Symbol-Tabelle (prim/sec)", OptimisticUpdate = true },
        new() { Name = "symcd",     Group = ConsoleCommandGroup.GPS, Type = ConsoleCommandType.Text,
                Description = "APRS Symbol-Spalte", OptimisticUpdate = true },

        // ── Netzwerk ─────────────────────────────────────────────────────
        new() { Name = "mesh",      Group = ConsoleCommandGroup.Netzwerk, Type = ConsoleCommandType.Toggle,
                Description = "Mesh Relay",
                ParsePattern = @"\.\.\.MESH\s+(on|off)", OptimisticUpdate = true },
        new() { Name = "webserver", Group = ConsoleCommandGroup.Netzwerk, Type = ConsoleCommandType.Toggle,
                Description = "Webserver",
                ParsePattern = @"Webserver\s+(on|off)", OptimisticUpdate = true },
        new() { Name = "webpwd",    Group = ConsoleCommandGroup.Netzwerk, Type = ConsoleCommandType.Text,
                Description = "Webserver Passwort (none = deaktivieren)", OptimisticUpdate = true },
        new() { Name = "gateway",   Group = ConsoleCommandGroup.Netzwerk, Type = ConsoleCommandType.Toggle,
                Description = "Gateway Modus",
                ParsePattern = @"Gateway\s+(on|off)", OptimisticUpdate = true },
        new() { Name = "nomsgall",  Group = ConsoleCommandGroup.Netzwerk, Type = ConsoleCommandType.Toggle,
                Description = "'*'-Nachrichten auf Display",
                ParsePattern = @"NOMSGALL\s+(on|off)", OptimisticUpdate = true },
        new() { Name = "setgrc",    Group = ConsoleCommandGroup.Netzwerk, Type = ConsoleCommandType.Text,
                Description = "Gruppen setzen (z.B. 9;26;)", OptimisticUpdate = true },
        new() { Name = "netconsole",Group = ConsoleCommandGroup.Netzwerk, Type = ConsoleCommandType.Toggle,
                Description = "Net Console (Port 2323)", OptimisticUpdate = true,
                StatusCommand = "netconsole",
                ParsePattern = @"net console is (on|off)" },
        new() { Name = "passwd",    Group = ConsoleCommandGroup.Netzwerk, Type = ConsoleCommandType.Text,
                Description = "Net Console Passwort (none = leer)", OptimisticUpdate = true },
        new() { Name = "extudp",    Group = ConsoleCommandGroup.Netzwerk, Type = ConsoleCommandType.Toggle,
                Description = "Ext. UDP", OptimisticUpdate = true },
        new() { Name = "extudpip",  Group = ConsoleCommandGroup.Netzwerk, Type = ConsoleCommandType.Text,
                Description = "Ext. UDP Ziel-IP (none = deaktivieren)", OptimisticUpdate = true,
                SuggestLocalIp = true },
        new() { Name = "setssid",   Group = ConsoleCommandGroup.Netzwerk, Type = ConsoleCommandType.Text,
                Description = "WLAN SSID (none = deaktivieren)", OptimisticUpdate = true },
        new() { Name = "setpwd",    Group = ConsoleCommandGroup.Netzwerk, Type = ConsoleCommandType.Text,
                Description = "WLAN Passwort (none = leer)", OptimisticUpdate = true },
        new() { Name = "setownip",  Group = ConsoleCommandGroup.Netzwerk, Type = ConsoleCommandType.Text,
                Description = "Statische IP", OptimisticUpdate = true },
        new() { Name = "setowngw",  Group = ConsoleCommandGroup.Netzwerk, Type = ConsoleCommandType.Text,
                Description = "Gateway IP", OptimisticUpdate = true },
        new() { Name = "setownms",  Group = ConsoleCommandGroup.Netzwerk, Type = ConsoleCommandType.Text,
                Description = "Subnetzmaske", OptimisticUpdate = true },
        new() { Name = "setowndns", Group = ConsoleCommandGroup.Netzwerk, Type = ConsoleCommandType.Text,
                Description = "DNS-Server IP", OptimisticUpdate = true },
        new() { Name = "setownntp", Group = ConsoleCommandGroup.Netzwerk, Type = ConsoleCommandType.Text,
                Description = "NTP-Server IP", OptimisticUpdate = true },
        new() { Name = "wifiap",    Group = ConsoleCommandGroup.Netzwerk, Type = ConsoleCommandType.Toggle,
                Description = "WLAN Access Point", OptimisticUpdate = true },
        new() { Name = "btcode",    Group = ConsoleCommandGroup.Netzwerk, Type = ConsoleCommandType.Value,
                Description = "Bluetooth PIN", Min = 0, Max = 999999, Step = 1, OptimisticUpdate = true },

        // ── Debug ─────────────────────────────────────────────────────────
        new() { Name = "debug",        Group = ConsoleCommandGroup.Debug, Type = ConsoleCommandType.Toggle,
                Description = "Debug-Ausgabe",
                ParsePattern = @"\.\.\.DEBUG\s+(on|off)", OptimisticUpdate = true },
        new() { Name = "loradebug",    Group = ConsoleCommandGroup.Debug, Type = ConsoleCommandType.Toggle,
                Description = "LoRa Debug",
                ParsePattern = @"LORADEBUG\s+(on|off)", OptimisticUpdate = true },
        new() { Name = "bledebug",     Group = ConsoleCommandGroup.Debug, Type = ConsoleCommandType.Toggle,
                Description = "BLE Debug",
                ParsePattern = @"BLEDEBUG\s+(on|off)", OptimisticUpdate = true },
        new() { Name = "wxdebug",      Group = ConsoleCommandGroup.Debug, Type = ConsoleCommandType.Toggle,
                Description = "WX/Wetter Debug",
                ParsePattern = @"WXDEBUG\s+(on|off)", OptimisticUpdate = true },
        new() { Name = "gpsdebug",     Group = ConsoleCommandGroup.Debug, Type = ConsoleCommandType.Toggle,
                Description = "GPS Debug",
                ParsePattern = @"GPSDEBUG\s+(on|off)", OptimisticUpdate = true },
        new() { Name = "softserdebug", Group = ConsoleCommandGroup.Debug, Type = ConsoleCommandType.Toggle,
                Description = "SoftSerial Debug",
                ParsePattern = @"SOFTSERDEBUG\s+(on|off)", OptimisticUpdate = true },
        new() { Name = "display",      Group = ConsoleCommandGroup.Debug, Type = ConsoleCommandType.Toggle,
                Description = "Display aktiv",
                ParsePattern = @"\.\.\.DISPLAY\s+(on|off)", OptimisticUpdate = true },
        new() { Name = "posted",       Group = ConsoleCommandGroup.Debug, Type = ConsoleCommandType.Action,
                Description = "Posted-Status anzeigen" },

        // ── SoftSerial ────────────────────────────────────────────────────
        new() { Name = "softser",     Group = ConsoleCommandGroup.System, Type = ConsoleCommandType.Toggle,
                Description = "SoftSerial (on/off/send/app/baud/…)", OptimisticUpdate = true },
        new() { Name = "softserread", Group = ConsoleCommandGroup.System, Type = ConsoleCommandType.Toggle,
                Description = "SoftSerial RX-Ausgabe", OptimisticUpdate = true },

        // ── Spectrum-Scan ─────────────────────────────────────────────────
        new() { Name = "spectrum",    Group = ConsoleCommandGroup.LoRa, Type = ConsoleCommandType.Action,
                Description = "Spektrum-Scan starten", NeedsConfirm = true },

        // ── SS ────────────────────────────────────────────────────────────
        new() { Name = "SS",          Group = ConsoleCommandGroup.Sensoren, Type = ConsoleCommandType.Toggle,
                Description = "SS-Sensor", OptimisticUpdate = true },

        // ── GPS
        new() { Name = "gps",      Group = ConsoleCommandGroup.GPS, Type = ConsoleCommandType.Toggle,
                Description = "GPS Chip aktiv", OptimisticUpdate = true },
        new() { Name = "track",    Group = ConsoleCommandGroup.GPS, Type = ConsoleCommandType.Toggle,
                Description = "SmartBeaconing (Tracking)", OptimisticUpdate = true },

        // ── Hardware / GPIO ───────────────────────────────────────────────
        new() { Name = "button",   Group = ConsoleCommandGroup.System, Type = ConsoleCommandType.Text,
                Description = "User-Button GPIO PIN (gpio 99)", OptimisticUpdate = true },
        new() { Name = "analog",   Group = ConsoleCommandGroup.System, Type = ConsoleCommandType.Text,
                Description = "Analog PIN / factor / check", OptimisticUpdate = true },

        // ── Sensoren ──────────────────────────────────────────────────────
        new() { Name = "bmp",     Group = ConsoleCommandGroup.Sensoren, Type = ConsoleCommandType.Toggle,
                Description = "BMP280 Drucksensor", OptimisticUpdate = true },
        new() { Name = "bme",     Group = ConsoleCommandGroup.Sensoren, Type = ConsoleCommandType.Toggle,
                Description = "BME280 Feuchte/Druck", OptimisticUpdate = true },
        new() { Name = "680",     Group = ConsoleCommandGroup.Sensoren, Type = ConsoleCommandType.Toggle,
                Description = "BME680 Luftqualität", OptimisticUpdate = true },
        new() { Name = "811",     Group = ConsoleCommandGroup.Sensoren, Type = ConsoleCommandType.Toggle,
                Description = "CCS811 CO₂-Sensor", OptimisticUpdate = true },
        new() { Name = "onewire", Group = ConsoleCommandGroup.Sensoren, Type = ConsoleCommandType.Toggle,
                Description = "OneWire (DS18xxx)", OptimisticUpdate = true },
        new() { Name = "bmx",     Group = ConsoleCommandGroup.Sensoren, Type = ConsoleCommandType.Action,
                Description = "Alle BMx Sensoren deaktivieren", NeedsConfirm = true },

        // ── Telemetrie ────────────────────────────────────────────────────
        new() { Name = "ptime",  Group = ConsoleCommandGroup.Telemetrie, Type = ConsoleCommandType.Value,
                Description = "Mess-Intervall", Unit = "min", Min = 1, Max = 60, Step = 1,
                OptimisticUpdate = true },
        new() { Name = "values", Group = ConsoleCommandGroup.Telemetrie, Type = ConsoleCommandType.Text,
                Description = "Telemetrie-Kanäle (press,hum,temp,onewire,co2)", OptimisticUpdate = true },
        new() { Name = "parm",   Group = ConsoleCommandGroup.Telemetrie, Type = ConsoleCommandType.Text,
                Description = "Mess-Parameternamen (tm1..tm5, kommagetrennt)", OptimisticUpdate = true },
        new() { Name = "unit",   Group = ConsoleCommandGroup.Telemetrie, Type = ConsoleCommandType.Text,
                Description = "Einheiten (V,A,mV,… kommagetrennt)", OptimisticUpdate = true },
        new() { Name = "format", Group = ConsoleCommandGroup.Telemetrie, Type = ConsoleCommandType.Text,
                Description = "Dezimalstellen (1,1,1,1,1)", OptimisticUpdate = true },
        new() { Name = "eqns",   Group = ConsoleCommandGroup.Telemetrie, Type = ConsoleCommandType.Text,
                Description = "Gleichungen (0,1,0, ...)", OptimisticUpdate = true },
    ];
}
