# add-french.ps1
# Adds French translations to all Loc.T() calls in the project.
# Pattern: Loc.T("de", "en", "it", "es") -> Loc.T("de", "en", "it", "es", "fr")
# Calls that already have 5 arguments are skipped.

$fr = @{
    # A
    "ACK" = "ACK"
    "ACK delivery" = "Livraison ACK"
    "Accept" = "Accepter"
    "Access denied" = "Accès refusé"
    "Actions" = "Actions"
    "Active" = "Actif"
    "Add" = "Ajouter"
    "Add command" = "Ajouter commande"
    "Add node" = "Ajouter nœud"
    "Add to watchlist" = "Ajouter à la liste"
    "AI" = "IA"
    "AI API Key" = "Clé API IA"
    "AI Model" = "Modèle IA"
    "AI Provider" = "Fournisseur IA"
    "AI Search" = "Recherche IA"
    "AI Summary" = "Résumé IA"
    "All" = "Tous"
    "All direct QSOs" = "Tous les QSO directs"
    "Antenna" = "Antenne"
    "Antenna gain" = "Gain antenne"
    "Antenna height" = "Hauteur antenne"
    "Antenna type" = "Type antenne"
    "Apply" = "Appliquer"
    "Auto-Reply" = "Réponse auto"
    "Auto-reply enabled" = "Réponse auto activée"
    "Auto-reply text" = "Texte réponse auto"

    # B
    "Baud rate" = "Débit"
    "Beacon" = "Balise"
    "Beacon enabled" = "Balise activée"
    "Beacon group" = "Groupe balise"
    "Beacon interval" = "Intervalle balise"
    "Beacon text" = "Texte balise"
    "Bot" = "Bot"
    "Bot commands" = "Commandes bot"
    "Bot enabled" = "Bot activé"
    "Broadcast" = "Diffusion"

    # C
    "Cable length" = "Longueur câble"
    "Cable type" = "Type câble"
    "Callsign" = "Indicatif"
    "Cancel" = "Annuler"
    "Certificate" = "Certificat"
    "Chat" = "Chat"
    "Clear" = "Effacer"
    "Clear Cache" = "Vider le cache"
    "Close" = "Fermer"
    "COM Port" = "Port COM"
    "Command" = "Commande"
    "Connect" = "Connecter"
    "Connected" = "Connecté"
    "Console" = "Console"
    "Copy" = "Copier"
    "Coverage" = "Couverture"
    "Create" = "Créer"

    # D
    "Database" = "Base de données"
    "Date" = "Date"
    "Delete" = "Supprimer"
    "Description" = "Description"
    "Device IP" = "IP appareil"
    "Device Port" = "Port appareil"
    "Direct" = "Direct"
    "Direct message" = "Message direct"
    "Disabled" = "Désactivé"
    "Disconnect" = "Déconnecter"
    "Disconnected" = "Déconnecté"
    "Done" = "Terminé"
    "Download" = "Télécharger"

    # E
    "Edit" = "Modifier"
    "Enabled" = "Activé"
    "Enter command …" = "Entrer commande …"
    "Enter manually …" = "Saisir manuellement …"
    "Error" = "Erreur"
    "Export" = "Exporter"

    # F
    "Fingerprint" = "Empreinte"
    "Firmware" = "Firmware"
    "Frequency" = "Fréquence"

    # G
    "Generate" = "Générer"
    "Group" = "Groupe"
    "Group filter" = "Filtre groupe"

    # H
    "Help" = "Aide"
    "History" = "Historique"
    "Hours" = "Heures"

    # I
    "Import" = "Importer"
    "Info" = "Info"
    "Interval" = "Intervalle"

    # L
    "Language" = "Langue"
    "Last seen" = "Vu en dernier"
    "Listen IP" = "IP écoute"
    "Listen Port" = "Port écoute"
    "Load" = "Charger"
    "Log" = "Journal"
    "LoRa" = "LoRa"

    # M
    "Map" = "Carte"
    "Message" = "Message"
    "Model" = "Modèle"
    "Monitor" = "Moniteur"
    "More info" = "Plus d'infos"

    # N
    "Name" = "Nom"
    "New" = "Nouveau"
    "No" = "Non"
    "No packet yet" = "Aucun paquet"
    "Node" = "Nœud"
    "Not connected" = "Non connecté"

    # O
    "OK" = "OK"
    "Online" = "En ligne"
    "Open" = "Ouvrir"
    "OTA" = "OTA"

    # P
    "Password" = "Mot de passe"
    "Pause" = "Pause"
    "Please select" = "Veuillez sélectionner"
    "Port" = "Port"
    "Primary" = "Principal"
    "Provider" = "Fournisseur"

    # Q
    "QRZ" = "QRZ"
    "QSO" = "QSO"
    "QSO Summary" = "Résumé QSO"

    # R
    "Reboot" = "Redémarrer"
    "Refresh" = "Actualiser"
    "Remove" = "Supprimer"
    "Reset" = "Réinitialiser"
    "Response" = "Réponse"
    "Resume" = "Reprendre"

    # S
    "Save" = "Enregistrer"
    "Search" = "Rechercher"
    "Select node" = "Sélectionner nœud"
    "Send" = "Envoyer"
    "Send Beacon Now" = "Envoyer balise maintenant"
    "Send now" = "Envoyer maintenant"
    "Sending…" = "Envoi en cours…"
    "Serial Console" = "Console série"
    "Settings" = "Paramètres"
    "Show" = "Afficher"
    "Start OTA update – sends --ota-update to node and opens OTA web server" = "Démarrer mise à jour OTA – envoie --ota-update au nœud et ouvre le serveur web OTA"
    "Status" = "Statut"
    "Stop" = "Arrêter"
    "Summary" = "Résumé"

    # T
    "Temperature" = "Température"
    "Test" = "Tester"
    "Test Beacon" = "Tester balise"
    "Test Connection" = "Tester connexion"
    "Testing…" = "Test en cours…"
    "Text" = "Texte"
    "Time" = "Heure"
    "TLS" = "TLS"
    "Trust & save" = "Faire confiance & enregistrer"
    "Type" = "Type"

    # U
    "UI Language" = "Langue interface"
    "Unknown" = "Inconnu"
    "Unknown Certificate" = "Certificat inconnu"
    "Update" = "Mettre à jour"

    # V
    "Version" = "Version"

    # W
    "Watchlist" = "Liste de surveillance"
    "Webhook" = "Webhook"

    # Y
    "Yes" = "Oui"
    "Yes, reboot" = "Oui, redémarrer"

    # Longer UI strings
    "0 = unlimited (never refresh)" = "0 = illimité (ne jamais actualiser)"
    "About" = "À propos"
    "About page" = "Page À propos"
    "Access denied: wrong password" = "Accès refusé : mauvais mot de passe"
    "Add group label" = "Ajouter étiquette groupe"
    "Add node profile" = "Ajouter profil nœud"
    "All nodes" = "Tous les nœuds"
    "Antenna height (m)" = "Hauteur antenne (m)"
    "Auto-dismiss after" = "Masquer après"
    "Auto-reply enabled (first contact only)" = "Réponse auto activée (premier contact uniquement)"
    "Backup & Restore" = "Sauvegarde & Restauration"
    "Backup settings" = "Sauvegarder paramètres"
    "Baud rate (e.g. 115200)" = "Débit (ex. 115200)"
    "Beacon group (e.g. #OE)" = "Groupe balise (ex. #OE)"
    "Beacon interval (hours)" = "Intervalle balise (heures)"
    "Bot command name (without --)" = "Nom commande bot (sans --)"
    "Bot response text" = "Texte réponse bot"
    "Cable attenuation (dB/10m)" = "Atténuation câble (dB/10m)"
    "Cable length (m)" = "Longueur câble (m)"
    "Callsign (with SSID, e.g. OE1ABC-1)" = "Indicatif (avec SSID, ex. OE1ABC-1)"
    "Certificate fingerprint (SHA-256)" = "Empreinte certificat (SHA-256)"
    "Clear all messages" = "Effacer tous les messages"
    "Collapse all" = "Tout réduire"
    "COM port (e.g. COM3 or /dev/ttyUSB0)" = "Port COM (ex. COM3 ou /dev/ttyUSB0)"
    "Connect to node" = "Connecter au nœud"
    "Connection refused" = "Connexion refusée"
    "Console mode" = "Mode console"
    "Copy to clipboard" = "Copier dans le presse-papiers"
    "CQ detection" = "Détection CQ"
    "CQ detection enabled" = "Détection CQ activée"
    "Database provider" = "Fournisseur base de données"
    "Date from" = "Date début"
    "Date to" = "Date fin"
    "Delete node" = "Supprimer nœud"
    "Device IP address" = "Adresse IP appareil"
    "Device port (UDP)" = "Port appareil (UDP)"
    "Direct message tab" = "Onglet message direct"
    "Display name" = "Nom affiché"
    "Download backup" = "Télécharger sauvegarde"
    "EIRP (dBm)" = "PIRE (dBm)"
    "Enable serial console" = "Activer console série"
    "Enable TLS console" = "Activer console TLS"
    "Enter command …" = "Entrer commande …"
    "Enter manually …" = "Saisir manuellement …"
    "Enter text …" = "Saisir texte …"
    "Expand all" = "Tout développer"
    "Export bot commands" = "Exporter commandes bot"
    "Filter by date" = "Filtrer par date"
    "Filter by text" = "Filtrer par texte"
    "Fingerprint saved" = "Empreinte enregistrée"
    "Free-space range (km)" = "Portée espace libre (km)"
    "Frequency (MHz)" = "Fréquence (MHz)"
    "Gateway" = "Passerelle"
    "Generate summary" = "Générer résumé"
    "Global search" = "Recherche globale"
    "Group filter enabled" = "Filtre groupe activé"
    "Group labels" = "Étiquettes groupe"
    "Group message" = "Message groupe"
    "Hide" = "Masquer"
    "History (paginated)" = "Historique (paginé)"
    "Host / IP" = "Hôte / IP"
    "Import bot commands" = "Importer commandes bot"
    "Import settings" = "Importer paramètres"
    "InfluxDB bucket" = "Bucket InfluxDB"
    "InfluxDB token" = "Jeton InfluxDB"
    "InfluxDB URL" = "URL InfluxDB"
    "Interval (hours, min. 1)" = "Intervalle (heures, min. 1)"
    "Last" = "Dernier"
    "Last seen" = "Vu en dernier"
    "Listen IP (0.0.0.0 = all interfaces)" = "IP écoute (0.0.0.0 = toutes interfaces)"
    "Listen port (UDP)" = "Port écoute (UDP)"
    "Live Map" = "Carte en direct"
    "Load more" = "Charger plus"
    "Local UDP port" = "Port UDP local"
    "LoRa debug highlighting on/off" = "Mise en évidence LoRa debug on/off"
    "Manual" = "Manuel"
    "Map settings" = "Paramètres carte"
    "Max. age (days, 0 = unlimited)" = "Âge max. (jours, 0 = illimité)"
    "Max. messages for AI summary" = "Nb max. messages pour résumé IA"
    "Message history" = "Historique messages"
    "Message input" = "Saisie message"
    "Messages" = "Messages"
    "MH list" = "Liste MH"
    "MH max. age (hours)" = "Âge max. MH (heures)"
    "Monitor max. messages" = "Max. messages moniteur"
    "MQTT" = "MQTT"
    "MQTT broker" = "Courtier MQTT"
    "MQTT enabled" = "MQTT activé"
    "MQTT password" = "Mot de passe MQTT"
    "MQTT port" = "Port MQTT"
    "MQTT prefix" = "Préfixe MQTT"
    "MQTT username" = "Nom utilisateur MQTT"
    "MySQL connection string" = "Chaîne connexion MySQL"
    "My callsign" = "Mon indicatif"
    "My locator" = "Mon localisateur"
    "New direct message from" = "Nouveau message direct de"
    "Next page" = "Page suivante"
    "No messages" = "Aucun message"
    "No packet yet" = "Aucun paquet encore"
    "Node name" = "Nom nœud"
    "Node port (UDP)" = "Port nœud (UDP)"
    "Node settings" = "Paramètres nœud"
    "Not connected" = "Non connecté"
    "OTA update started" = "Mise à jour OTA démarrée"
    "Own callsign" = "Mon indicatif"
    "Own messages align left" = "Messages propres alignés à gauche"
    "Page" = "Page"
    "Password (max. 14 chars)" = "Mot de passe (max. 14 car.)"
    "Pause output (new lines still buffered)" = "Pause sortie (nouvelles lignes toujours mises en mémoire)"
    "Previous page" = "Page précédente"
    "Primary node" = "Nœud principal"
    "QRZ password" = "Mot de passe QRZ"
    "QRZ username" = "Nom utilisateur QRZ"
    "Quick texts" = "Textes rapides"
    "Reboot node – sends --reboot to node" = "Redémarrer nœud – envoie --reboot au nœud"
    "Reboot node?" = "Redémarrer le nœud ?"
    "Regenerate" = "Régénérer"
    "Remove node" = "Supprimer nœud"
    "Restore settings" = "Restaurer paramètres"
    "Resume output (scroll re-enabled)" = "Reprendre sortie (défilement réactivé)"
    "Save fingerprint in node settings to permanently trust this node." = "Enregistrez l'empreinte dans les paramètres du nœud pour faire confiance en permanence à ce nœud."
    "Save settings" = "Enregistrer paramètres"
    "Search all direct QSOs" = "Rechercher tous les QSO directs"
    "Search in history…" = "Rechercher dans l'historique…"
    "Select node" = "Sélectionner nœud"
    "Send Beacon Now" = "Envoyer balise maintenant"
    "Send message" = "Envoyer message"
    "Serial Console" = "Console série"
    "Serial port" = "Port série"
    "Server URL" = "URL serveur"
    "Settings saved" = "Paramètres enregistrés"
    "Show gateway" = "Afficher passerelle"
    "Show own position" = "Afficher ma position"
    "Signal strength" = "Force du signal"
    "SNR" = "SNR"
    "Sound" = "Son"
    "Sound enabled" = "Son activé"
    "Station / HF parameters" = "Paramètres station / HF"
    "Station parameters" = "Paramètres station"
    "System margin (dB)" = "Marge système (dB)"
    "Telemetry" = "Télémétrie"
    "Telemetry enabled" = "Télémétrie activée"
    "Telemetry interval (minutes)" = "Intervalle télémétrie (minutes)"
    "Test auto-reply" = "Tester réponse auto"
    "Test bot command" = "Tester commande bot"
    "The node will be rebooted. The TLS connection will be disconnected afterwards." = "Le nœud va redémarrer. La connexion TLS sera déconnectée ensuite."
    "The node is starting the OTA web server. Page opens in" = "Le nœud démarre le serveur web OTA. La page s'ouvre dans"
    "Timeout" = "Expiration"
    "TLS certificate fingerprint" = "Empreinte certificat TLS"
    "TLS Console" = "Console TLS"
    "TLS enabled" = "TLS activé"
    "TLS password" = "Mot de passe TLS"
    "TLS port" = "Port TLS"
    "Token usage" = "Utilisation tokens"
    "Total" = "Total"
    "Trust & save" = "Faire confiance & enregistrer"
    "TX power (dBm)" = "Puissance TX (dBm)"
    "Unknown Certificate" = "Certificat inconnu"
    "Upload" = "Téléverser"
    "User-defined commands" = "Commandes personnalisées"
    "Voice" = "Voix"
    "Voice announcements" = "Annonces vocales"
    "Voice enabled" = "Voix activée"
    "Watchlist enabled" = "Liste surveillance activée"
    "Webhook enabled" = "Webhook activé"
    "Webhook URL" = "URL webhook"
    "Yes, reboot" = "Oui, redémarrer"

    # Full sentences from Telnet/Chat/Settings
    "Verbinden" = "Se connecter"
    "Trennen" = "Déconnecter"
    "Verbunden" = "Connecté"
    "Getrennt" = "Déconnecté"
    "Löschen" = "Effacer"
    "Senden" = "Envoyer"
    "Weiter" = "Continuer"
    "Abbrechen" = "Annuler"
    "Vertrauen & speichern" = "Faire confiance & enregistrer"
    "Zuletzt" = "Vu en dernier"
    "Noch kein Paket" = "Aucun paquet encore"
    "Ja, neu starten" = "Oui, redémarrer"
    "Node wählen" = "Choisir nœud"
    "OTA-Update starten – sendet --ota-update an den Node und öffnet den OTA-Webserver" = "Démarrer mise à jour OTA – envoie --ota-update au nœud et ouvre le serveur web OTA"
    "Node neu starten – sendet --reboot an den Node" = "Redémarrer le nœud – envoie --reboot au nœud"
    "Node neu starten?" = "Redémarrer le nœud ?"
    "Der Node wird neu gestartet. Die TLS-Verbindung wird danach getrennt." = "Le nœud va redémarrer. La connexion TLS sera déconnectée ensuite."
    "OTA-Update wird gestartet" = "Démarrage mise à jour OTA"
    "Der Node startet den OTA-Webserver. Die Seite öffnet sich in" = "Le nœud démarre le serveur web OTA. La page s'ouvre dans"
    "Sekunden" = "secondes"
    "Unbekanntes Zertifikat" = "Certificat inconnu"
    "Fingerprint in den Node-Einstellungen speichern, um diesen Node dauerhaft zu vertrauen." = "Enregistrez l'empreinte dans les paramètres du nœud pour faire confiance en permanence à ce nœud."
    "Befehl eingeben …" = "Entrer commande …"
    "Nicht verbunden" = "Non connecté"
    "Ausgabe fortsetzen (Scroll wieder aktiv)" = "Reprendre la sortie (défilement réactivé)"
    "Ausgabe pausieren (neue Zeilen kommen weiter rein)" = "Mettre en pause (nouvelles lignes toujours reçues)"
    "LoRa-Debug-Hervorhebung ein/aus" = "Mise en évidence LoRa debug on/off"
    "Oberflächensprache" = "Langue de l'interface"
    "Sprache" = "Langue"
}

Write-Host "Dictionary loaded with $($fr.Count) entries"
